# Generated by Django 4.1.5 on 2023-01-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Financial_control",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.IntegerField()),
                ("data", models.IntegerField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cpf", models.IntegerField()),
                ("cartão", models.IntegerField()),
                ("hora", models.IntegerField()),
                ("dono_da_loja", models.CharField(max_length=15)),
                ("nome_loja", models.CharField(max_length=20)),
            ],
        ),
    ]
