# Generated by Django 4.1.5 on 2023-01-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Financial_control", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financial_control",
            name="cartão",
            field=models.CharField(max_length=12),
        ),
    ]
